name: Main

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - master
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - master

#env:
#  CARGO_TERM_COLOR:  always

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --all-targets -- -D clippy::all

  test:
    strategy:
      matrix:
        # rust: [stable, beta, nightly]
        # The stable and beta would have different error text that are all correct.
        # Just test against beta for now
        rust: [beta]
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.rust != 'stable' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Test
        run: cargo test

  publish-docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [codestyle, lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Generate Docs
        run: |
          cargo doc --no-deps
          echo "<meta http-equiv=refresh content=0;url=`echo ${{ github.repository  }} | cut -d / -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc

  publish-crate:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [codestyle, lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish
        run: |
          pushd dynomite-derive
          cargo publish --token ${{ secrets.CRATES_TOKEN }}
          popd
          # eventual consistency dictates we wait a bit before publishing
          # a crate that depends on the above
          sleep 20
          pushd dynomite
          cargo publish --token ${{ secrets.CRATES_TOKEN }}
          popd
